data:
  orig_data_dir: "/kaggle/input/bananaripeness/Original"
  synth_data_dir: "/kaggle/input/bananaripeness/Synthetic"
  batch_size: 32
  img_size: 224
  num_workers: 4
  imagenet_mean: [0.485, 0.456, 0.406]
  imagenet_std: [0.229, 0.224, 0.225]

model:
  num_classes: 4
  pretrained: true
  backbone: "resnet34"

training:
  epochs: 10
  lr: 0.0001
  gamma: 0.94
  warmup: true
  warmup_epochs: 5
  warmup_threshold: 0.9
  lambda_creda: 1.0
  lambda_entropy: 0.0
  use_uncertainty: true
  sigma: "auto"
  use_amp: true
  device: "cuda"

experiment:
  name: "base_experiment"
  version: 1
  output_dir: "outputs/experiment_1"