data:
  orig_data_dir: "/kaggle/input/bananaripeness/Original"
  synth_data_dir: "/kaggle/input/bananaripeness/Synthetic"
  batch_size: 32
  img_size: 224
  num_workers: 4

model:
  num_classes: 4
  pretrained: true
  backbone: "resnet34"

training:
  epochs: 10
  lr: 0.0001
  lambda_creda: 1.0
  lambda_entropy: 0.05
  use_uncertainty: true
  sigma: "auto"
  use_amp: true
  device: "cuda"